from setuptools import setup, find_packages

setup(
    name='empir19nrm02',
    version='0.1.0',
    packages= find_packages(),
    url='https://github.com/empir19nrm02/empir19nrm02',
    license='',
    author='Udo Krüger',
    author_email='udo.krueger@technoteam.de',
    description='Meausrement Uncertainty for EMPIR 19nrm02',
    keywords = ['color', 'colorimetry','photometry','CIE','spectral data', 'measurement uncertainty'],

	install_requires=[
        'numpy',
        'math',
		'scipy',
		'matplotlib',
		'pyxll',
        'luxpy',
        'pandas',
        'os',
        'dataclasses',
        'copy',
        'traceback',
        'pickle',
        'mpl_toolkits',
        'seaborn',
        'sigfig',
      ],
	package_data={'': [	'data/spd/*.csv', 'data/spd/*.txt', 
						'data/res/*.csv', 'data/res/*.txt', 
						'data/corr/*.csv', 'data/corr/*.xlsx']},
    include_package_data = True,
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Programming Language :: Python :: 3',
        ],
    python_requires='>=3.10',
)